### ISSUE TITLE
Whether can recognize Chinese with chi_sim.traineddata

### ISSUE THREAD

**Issue by yaojingzhe** [dynobo/normcap#104]
Dear Author:

May I use normcap to recognize Chinese on screan with chi_sim.traineddata?
I tried, but I couldn't recognize Chinese
I saved Chinese screen to cn.jpg 
and use CMD: tesseract cn.jpg cn -l chi_sim
I got cn.txt and recognized Chinese

Should I set normcap to recognize Chinese? no config file to set.

I downloaded normcap_win64.zip

Thank you very much for your reply.

System：windows 10

**Comment by dynobo** [comment]
Hi @yaojingzhe, 

Yes, in general you can use NormCap will all language available for tesseract. But the compiled binary-releases currently only include german and english support (because the file size of the language data is quite large).

If you answer the following questions, I might be able to help you setting up the support for chinese:
1. What's your operating system? MacOS? Linux? Windows 10?
2. Did you install normcap using the `pip install normcap` method and installed tesseract independently?
3. Or did you use one of the provided normcap binary releases? If yes, which version?
 
PS: Now that I know that some users are interested in Chinese, I'm going to include `chi-sim` in the next release, too, but this might take some time... :-)

**Comment by dynobo** [comment]
Hi @yaojingzhe,

You have two options:

**1. Extend your portable version `normcap_win64.zip` with chinese**
The binary releases use the _included_ tesseract version (which comes only with english and german currently).
But you can download the [chi_sim language data file](https://github.com/tesseract-ocr/tessdata) and drop it in the folder `/normcap/tessdata/` of the portable version. Then you can start normcap with the `-l` or `--lang` parameter to set the language, e.g. `normcap -l chi_sim` for chinese or `normcap -l chi_sim+eng` for chinese _and_ english support.

**2. Use tesseract installed on system with normcap's pip package**
If you install normcap through `pip install normcap`, it will use the systems tesseract with all it's installed language data. So as you have a working tesseract installation, you should be able to run with chinese support using the language argument `normcap -l chi_sim`.

Caveat: On windows, normcap is only tested with tesseract 4.1, I do not know if the 5alpha will work. You can grab the installer from 4.1 here:  [tesseract-ocr-w32-setup-v4.1.0.20190314.exe](https://digi.bib.uni-mannheim.de/tesseract/) along with the [language data](https://github.com/tesseract-ocr/tessdata). But if you test run with 5alpha first, I certainly would be intererested  to know, if it works :-)

Please let me know, if this helped you!

**Comment by yaojingzhe** [comment]
Dear author:

I downloaded normcap_win64.zip and use normcap with -l chi_sim, it's work well and can recognize both Chinese and English. I will soon try install normcop trouth pip install normcap to test tesseract 5alpha and tell you the result.

Your program is so excellent than help me greatful.

And also thank you for your kindness.
