### ISSUE TITLE
Please help testing the new beta version 0.2.0-b2

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#114]
I've published a 0.2.0-b2 beta-release, with major changes.

**It would be really great if you could help testing it and provide feedback (positive or negative) here in this ticket**

### Changes

- (Almost) total rewrite of NormCap!
- Switch from Tk to Qt as UI Framework
- Easy to use binary package releases (no hassle with dependencies anymore!)
- Better support for HiDPI
- Better support multi monitor setups (MacOS)
- Better support for Wayland (Linux)
- Experimental system tray support (start with `--tray` )

### Changes since 0.2.0-b1

- Fix capturing from new system tray on Linux
- Styled the Windows installer
- Incorporated necessary `tesserocr` dependencies into packages

### How to test

Either [download the binary/installer](https://github.com/dynobo/normcap/releases/tag/v0.2.0-b2) _or_ build from source off the branch [feature/switch-to-qt5](https://github.com/dynobo/normcap/tree/feature/switch-to-qt5).

The updated [README](https://github.com/dynobo/normcap/tree/feature/switch-to-qt5) provides additional information, as well as the new [FAQs](https://github.com/dynobo/normcap/blob/feature/switch-to-qt5/FAQ.md).

**Comment by thecoder-001** [comment]
Seems to be working well on macOS and the capture from system tray bug seems to be fixed too.
Would test on Gnome later in the evening for any regressions.

**Comment by thecoder-001** [comment]
On the other hand, the package size is looking a bit concerning (especially for macOS, where the final package takes about ~600MB in disk). Though I would be installing the module through pip, those who would end up using the prebuilt binaries would find the application size a bit too large.

A lot of the space seems to be occupied by pyside2 which seems to include a lot of unneeded stuff.
One prominent example is `QtWebEngineCore.framework` which consumes 240mb in itself and is not required by the project.
Removing the said library manually doesn't effects the functioning of the project and although crude, seems to be an effective solution (maybe the only viable one too, since there doesn't seems to be a way to programatically remove unneeded libs under briefcase).
Maybe something to consider before releasing a stable release?
Reference:
![Screenshot 2021-06-18 at 11 27 23 AM](https://user-images.githubusercontent.com/25097841/122513554-28666300-d028-11eb-992f-3690e40dd06c.png) ![Screenshot 2021-06-18 at 11 38 08 AM](https://user-images.githubusercontent.com/25097841/122514485-a9722a00-d029-11eb-816a-41546f4f0947.png)

**Comment by dynobo** [comment]
Thanks a lot for your comments, @thecoder-001. Especially your observations regarding the filesize are helpful, as I also think it's currently too large. I will definitely spend some time on this topic, and also ask the briefcase community about strategies to mitigate this.

**Comment by dynobo** [comment]
Thanks for the tests! I just published 0.2.0b3 (with drastically reduced file siue) as public beta on [pypi](https://pypi.org/project/normcap/) and [github](https://github.com/dynobo/normcap/releases/tag/v0.2.0b3).

Please report further problems as regular issues.
