### ISSUE TITLE
Screen is completly black with red border

### ISSUE THREAD

**Issue by Flying--Dutchman** [dynobo/normcap#126]
When launching NormCap as AppImg or as a python package, the screen turn black. All I see is the NormCap red border and menu. 

I can capture something, and the ocr part is working correctly, but I am unable to see what I'm capturing.

System:
 - Manjaro Linux 
 - 3 Monitors
 - Nvidea GPU

![image](https://user-images.githubusercontent.com/9158539/126519944-26dd93bf-02f3-4c19-bd65-82f5ab3bb2c4.png)

**Comment by dynobo** [comment]
Thanks for the bug report! Could you please provide info on:
- Version of your Manjaro
- What's your Desktop Environment? (Gnome, KDE, XFCE?)
That would help me to reproduce the bug.

**Comment by Flying--Dutchman** [comment]
Oh sorry, of course:

Manjaro: Pahvo 21.1.0
Desktop Enviroment: KDE Plasma 5.22.3  
Kernel: 5.4.131-1 64 Bit
QT-Version: 5.15.2

**Comment by dynobo** [comment]
Hi @Flying--Dutchman,

I just tried to reproduce the issues with Manjaro 21.0.7 KDE (Live CD), but everything was working as expected.

One question: Do you know if you current setup supports window transparency? I'm not familiar with KDE, but it [seem like](https://forum.manjaro.org/t/cant-enable-blur-transparency-effect/25229) this depends on the compositor as well as the used theme. 
It would really help me if I could reproduce the issue, so if you have any additional information on your settings that might help... :-)

**Some additional background on the issue:**

There are basically two options to "draw on the Desktop" above other applications: 

- A) Take a screenshot, of the full desktop, create a full screen window, use the screen shot as "background image" of this window and "draw" on that window.
- B) Create a (partially) transparent full screen window, put it on top of all other applications and then "draw" on the transparent area. 

I used method A) for NormCap v0.1.\*, but switched to method B) for NormCap v0.2.\*, mainly because it was difficult to avoid some issues with HiDPI (especially, if one monitor is HiDPI, and another is not), but also because it felt more natural when e.g. animations/videos keep moving and don't "freeze" like it does in A).

However, B) also turns out to have some downside, e.g. like this issue (black window if no transparency is available), but also #121 is a side-effect. That's why I'm thinking about supporting both methods (or even a hybrid approach), but I'm gonna need some weekends for that.

**Comment by Flying--Dutchman** [comment]
That did the trick! 

Appearently composer shut itself off a while ago. Restarted it and now everything works fine :+1:
