### ISSUE TITLE
How to set preferred languages under Linux?

### ISSUE THREAD

**Issue by sojusnik** [dynobo/normcap#141]
Using Ubuntu 21.04 and installed NormCap with `sudo apt install tesseract-ocr tesseract-ocr-eng tesseract-ocr-deu tesseract-ocr-rus libtesseract-dev libleptonica-dev python3-dev` and `pip install normcap`.

English text is recognized flawlessly, but German and Russian aren't, although the proper packages are installed.

My `/.config/normcap/settings.conf` contains:

```
[General]
color=#FF2E88
language=@Variant(\0\0\0\x7f\0\0\0\x18PySide::PyObjectWrapper\0\0\0\0\x14\x80\x4\x95\t\0\0\0\0\0\0\0\x8c\x3\x65ng\x94\x85\x94.)
mode=parse
notification=true
tray=false
update=true
```

I assume that I have to specify my preferred languages (ENG, DEU, RUS) there, but can't find an instruction for that.

Can you help?

**Comment by sojusnik** [comment]
Oh, just noticed the settings cog in the right upper corner, where you can select the languages. My fault, sorry!

**Comment by dynobo** [comment]
Oh, but  thanks for the (closed) bug report, nevertheless! I didn't notice the bad representation of the language option in the `settings.conf` before! As I'd prefer to have a human readable representation, I'll opened #143 and will track that there :-)

**Comment by johnblommers** [comment]
> Oh, just noticed the settings cog in the right upper corner, where you can select the languages. My fault, sorry!

This bit me too. That red gear is only present when the capture mode is active. It really properly SHOULD be situated in the top bar with the Capture and Exit menu items.

**Comment by dynobo** [comment]
@johnblommers , thanks for that feedback! 

The reasons why I didn't put it in the Tray Icon (top bar) were:
1. Not all systems support showing NormCap in the tray: Some Linux distributions might require additional software to show it, some desktop managers won't show it at all.
2. The Tray Icon is not visible on start of NormCap (for technical reasons). It only becomes visible once NormCap was minimized. Also it is optional (configurable in the settings), because of reason 1). 

Nevertheless, I have some ideas to improve the situation:
1. Introduce a simple "Intro"-guide that shows on first start of NormCap and explains common questions like changing language or where the result goes (clipboard). 
2. Add the menu to the tray icon _additionally_ (but this will neither help on first start nor on systems without Tray Icon)
3. Make the menu visually more noticable (but how?)

I'd be really interested to gather some feedback about those ideas (and others?) :slightly_smiling_face:

**Comment by johnblommers** [comment]
The intro guide is a good idea.

 So is adding the settings menu to the system tray.

When launching normcap consider displaying for a few seconds a little dialog box about where the settings  gear is located. Click Settings or click Dismiss.

 Also why not allow the system to show the normcap icon in the dock? The user  will see it. Then implement a right click on the icon to reveal a settings contextual menu.
