### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '95.000000'

### ISSUE THREAD

**Issue by typoman** [dynobo/normcap#170]
I get a traceback when I select the screen region. I installed `normcap` using pip. I'm sending this because at the end of traceback I was asked to send it here. I'm running OSX 10.15.7.

```
23:51:24 - ERROR   - normcap.utils          - L:105 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/normcap/gui/main_window.py", line 293, in _capture_to_ocr
    capture=self.capture,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/normcap/ocr.py", line 63, in __call__
    capture = self.extract(capture)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/normcap/ocr.py", line 82, in extract
    words = self.tsv_to_list_of_dicts(tsv_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/normcap/ocr.py", line 162, in tsv_to_list_of_dicts
    words[idx][key] = int(value)  # type: ignore # (casting on purpose)
ValueError: invalid literal for int() with base 10: '95.000000'
23:51:24 - ERROR   - normcap.utils          - L:107 - Please open an issue with the output above on https://github.com/dynobo/normcap/issues
```

When I change the mode to capture raw traceback changes to:
```
ValueError: invalid literal for int() with base 10: '45.408649'
```

**Comment by dynobo** [comment]
Hey, thanks for reporting this issue! :-)

Can you please check your tesseract version?: `brew info tesseract`.

Homebrew recently switched from tesseract 4 to 5, which seems to make problems together with the Python library tesserocr. If you have version 5, too, you could try to install version 4 as a workaround:
```          
brew tap-new $USER/local-tap
brew extract --version=4.1.3 tesseract $USER/local-tap
brew install tesseract@4.1.3
brew info tesseract
```

In the meanwhile I'm in the progress of a bigger update, which includes support for tesseract 5 for MacOS and should solve your issue permanently.

**Comment by artemgur** [comment]
I have the same issue on Manjaro with Tesseract 5

**Comment by dynobo** [comment]
Hi @artemgur, hi @typoman, this issue was addressed in the latest pre-release `NormCap v0.3.0-beta`. 
Would you mind [help testing `v0.3.0-beta`](https://github.com/dynobo/normcap/discussions/178) and report back, if it solves this issue? Thanks!

**Comment by dynobo** [comment]
I'm pinning this issue, because more people are reporting issues.

**Short summary:**

- The issue occurs when NormCap 0.2.* is used together with Tesseract 5.*, because NormCap currently only supports Tesseract up to version 4.
- The recommended workaround is to use [a prebuild version of NormCap 0.2.10](https://github.com/dynobo/normcap/releases/tag/v0.2.10), e.g. the AppImage for Linux. (Those packages have Tesseract 4 included)
- Another option would be to downgrade your system's Tesseract version, but this is not easy and can have unwanted side-effects, so only do this if you are knowing what you are doing.
- NormCap 0.3.* is being developed, a public beta is going to be released in the next two weeks. This version will be compatible with Tesseract 5 and introduces other benefits. So waiting might also be an option regarding this issue.

**Comment by dynobo** [comment]
The [NormCap v0.3.0b2](https://github.com/dynobo/normcap/releases/tag/v0.3.0b2) release should not have this issue anymore (it has support for Tesseract 5). Please give it a try, and report back, if it works!
