### ISSUE TITLE
Launch failed on macOS 12.3 MBA M1 Unknown error: 153

### ISSUE THREAD

**Issue by egigoka** [dynobo/normcap#205]
Version: 0.3.3

Error:
❯ open -a NormCap.app
The application /Applications/NormCap.app cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600000ba6b50 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

**Comment by dynobo** [comment]
Hi @egigoka, thanks for reporting this issue!

Unfortunately, I need some more information to figure out what's going on:

1. Did you allow NormCap, after it was blocked on first launch (because it's unsigned)?
   ![2022-03-27_20-32](https://user-images.githubusercontent.com/11071876/160295811-7c3b2db7-fd30-4fa1-a087-e8f77c474b2a.png)

2. Does NormCap has the rights for screen recording?
   ![2022-03-27_20-28](https://user-images.githubusercontent.com/11071876/160295829-f1c96fba-1e4e-4369-af8e-f74b2e4c863e.png)

3. Could you please run the following command and post its output?
    `system_profiler SPHardwareDataType SPSoftwareDataType`

That would help me a lot! :-)

**Comment by dynobo** [comment]
Please re-open, if this problem persists with the [latest release](https://github.com/dynobo/normcap/releases)
