### ISSUE TITLE
[Feature Request] Support Arabic Language

### ISSUE THREAD

**Issue by vzool** [dynobo/normcap#216]

**Comment by dynobo** [comment]
Hi @vzool , please take a look at the corresponding section in the FAQ: [How can I add additional languages?](https://dynobo.github.io/normcap/#faqs-languages)

Does this help you?

**Comment by vzool** [comment]
I used the prebuild packages on Mac OS 12.3.1 and here is the result:

[https://www.youtube.com/watch?v=bmZUh8dR7N4](https://www.youtube.com/watch?v=bmZUh8dR7N4)

**Comment by dynobo** [comment]
Sorry for pointing you to the FAQ, I forgot that Arabic should already be supported out of the box. :see_no_evil:

So no need to add any language files manually.

Could you please double check:
1. Are you using a recent version of Normcap (v0.3.3 or v0.3.4)?
2. Do you have "Arabic" selected as language in the settings menu? (see screenshot below)

Because for me it seems to be working:
![Screenshot 2022-06-08 at 17 36 01](https://user-images.githubusercontent.com/11071876/172659160-eb0d7463-6e36-44e4-8163-2db3a96d5750.png)

If it still does not work, please start NormCap through the command line and share the output here? Just run:

```sh
/Applications/NormCap.app/Contents/MacOS/NormCap -v debug
```

**Comment by vzool** [comment]
Thanks @dynobo
