### ISSUE TITLE
NormCap is unable to start due to a tesseract error

### ISSUE THREAD

**Issue by Bader-Idris** [dynobo/normcap#222]
After downloading the NormCap tool, I found an error attached to a secondary app which is tesseract ocr, after, that I installed it as if it was the reason, but it abropt me with this error, saying it wasn't able to start.

![image](https://user-images.githubusercontent.com/93044377/180611425-e9eca854-61fd-4b8a-8cc8-be90fe1b3489.png)

**Comment by dynobo** [comment]
Hi @Bader-Idris , thanks for reporting the issue! Just two more question:

1. Did I understand you correctly, that you have installed Tesseract OCR _independently_ of NormCap, e.g. because another App needs it or you use it directely?

2. Did you install NormCap using the installer (`.msi`) or via `pip install`?

I'm asking because both aspects might influence how NormCap is trying to start tesseract internally.

**Comment by Bader-Idris** [comment]
Initially, I just installed NormCap, but after seeing the error including the tesseract name, I installed it independently.

for the 2nd Q, I did the same, firstly as .msi and latterly by the terminal tool.

**Comment by dynobo** [comment]
I see. If the `.msi` package is used, one _should not_ install Tesseract, as it is bundled with the installer. While if NormCap is install via `pip` one _have to_ install Tesseract seperately.

Could you please do the following:

1. Make sure that the NormCap pip package is removed (`pip uninstall normcap`)
2. Uninstall Tesseract OCR (I think through "Add/remove programs"?)
3. Try to start the version you installed via the `.msi` installer through the Start Menu and post the initial error message (the one that mentioned tesseract)

Thanks a lot!

**Comment by Bader-Idris** [comment]
@dynobo I did exactly what you encouraged me to do, but unfortunately, it didn't work.
could it be because of installing xampp or python?

**Comment by dynobo** [comment]
@Bader-Idris , I released a new version yesterday. Could you please uninstall your current version, and then install the new [v0.3.5](https://github.com/dynobo/normcap/releases/tag/v0.3.5)?

If you still get an error on start, could you please post a screenshot of it?

**Comment by Bader-Idris** [comment]
It got the same error, by the way, my system is windows 11 pro N building is 22000
![image](https://user-images.githubusercontent.com/93044377/181852797-c6b2ad55-80ad-4079-b0d6-bab27fdaea34.png)

**Comment by dynobo** [comment]
@Bader-Idris , could you please try to launch NormCap from the command line and post the output? 
```cmd
C:\Users\<USER-NAME>\AppData\Local\Programs\NormCap\NormCap.exe -v debug
```
Hopefully this provides further information...

Thanks for your help and patience :smile:

**Comment by Bader-Idris** [comment]
![1](https://user-images.githubusercontent.com/93044377/182046770-e28626c2-398d-476a-8787-a50a2d7dd5e3.png)
![2](https://user-images.githubusercontent.com/93044377/182046775-bf21e815-cdf4-4cfd-9413-b6747863e6a0.png)
![3](https://user-images.githubusercontent.com/93044377/182046779-5cb722fd-cb3a-450f-8b73-57c1b880329c.png)
![4](https://user-images.githubusercontent.com/93044377/182046783-d43194b0-4ce0-4f61-905a-b83973d1ecf8.png)
![5](https://user-images.githubusercontent.com/93044377/182046789-6f88574a-d8b0-4413-83e9-a03973ec2222.png)



this is all of what I got after launching it.

**Comment by dynobo** [comment]
Hi @Bader-Idris, something seems a bit off with your installation, let's see if we can resolve this:

In your second screenshot, we see that you _did_ start NormCap with `NormCap.exe -v debug` in `C:\Users\<USER-NAME>\AppData\Local\Programs\NormCap\`, but what got _launched_ still looks like the path of the Python package: `'cli_args': 'C:\\Python310\\Scripts\\normcap -v debug'` (should be `[...]\AppData\Local\Programs\NormCap\NormCap.exe -v debug`). Also, `'is_briefcase_package': False` and `Start NormCap v0.3.4` (while you said you followed my instructions with v0.3.5) indicate, that still the Python package version is started.

(The fact, that `NormCap` still starts from inside the `AppData`-Folder might be because `C:\Python310\Scripts\` is in your `PATH` environment variable. You can verify this by running NormCap from somewhere else, e.g. `C:\users\<USER-NAME>\normcap.exe -v debug`.)

Could you please again try to uninstall the installer version (through Windows' "Add or remove Programs") _and_ the Python version (with `pip uninstall normcap`)? Please verify, that it is uninstalled by again trying to run `NormCap.exe` (should fail!).

If you have verified, that both Python package and Installer got removed, please try again to install NormCap using the `.msi`-installer. 

PS: What I forgot to mention: If you start the installed version of NormCap via `C:\Users\<USER-NAME>\AppData\Local\Programs\NormCap\NormCap.exe -v debug`, you should not see any output at all. Instead, a log file containing the output will be created in the same folder: `C:\Users\<USER-NAME>\AppData\Local\Programs\NormCap\NormCap.exe.log`)

Let me know how it went! :-)

**Comment by dynobo** [comment]
Could you please retry with the new release [NormCap v0.4.0](https://github.com/dynobo/normcap/releases/tag/v0.4.0)? It includes a different tesseract binary for Windows, which might solve some issues.

**Comment by Bader-Idris** [comment]
works perfectly.
but I figure that sometimes zeros aren't read well as:
10@vh; 
it read 2nd zero in 100vh as @ symbol, the zero type was slashed
![msedge_s9YtIJqNUG](https://user-images.githubusercontent.com/93044377/215582138-35978e16-e5b7-4092-9c05-3ddb7030ad22.png)

**Comment by dynobo** [comment]
Thanks for your feedback, @Bader-Idris, glad it's working for you now.

Regarding detection quality, I have written up some [tricks for improving detection quality in the FAQs](https://dynobo.github.io/normcap/#faqs-improve-detection), but in your case they probably won't help a lot...

**Comment by dynobo** [comment]
Closing, because the initial problem seems to be resolved. Please feel free to reopen, if it occurs again.
