### ISSUE TITLE
[FLATPAK] Normcap exception in Cinnamon

### ISSUE THREAD

**Issue by AEVE1001** [dynobo/normcap#230]
Hi, I downloaded Normcap from Flathub, yet after selecting the region to process, nothing happened.

I ran the program through the cli with _flatpak run com.github.dynobo.normcap_,  and after selecting the screen region, I got the following error:

_14:04:52 - ERROR   - normcap.screengrab.utils:96 - Exception when trying to get gnome-shell version_ 

My system is Linux Mint 20.3 with Cinnamon Desktop 5.2.7

NOTE: I think this is related to Bug #168, "Not Working with Linux Mint".

**Comment by dynobo** [comment]
Hi @AEVE1001 , thanks for reporting your problem.

If you _see_ the NormCap UI (red border) and _can_ select a region, it is most likely unrelated to #168 . The error you've posted, is most likely not a problem at all. (I'm going to downgrade it to a "warning", as "error" is misleading here.) When I tested on a fresh LinuxMint 21 with cinnamon 5.4.8, everything worked as expected.

Can you please try the following?

1. Check, if NormCap is indeed not working as intended? Due to the lack of description on FlatHub (#226), there can be some [misunderstanding on how NormCap works](https://github.com/dynobo/normcap/issues/224#issuecomment-1200134851): Shortly after selecting a region, the NormCap UI will disappear and the recognized text will be copied to your system clipboard and can be pasted somewhere with `CTRL+v`.
2. If it still doesn't work, please start NormCap from the command line with the debug flag and post the output:
   ```sh
   flatpak run com.github.dynobo.normcap -v debug
   ```

Does this help?

**Comment by AEVE1001** [comment]
My fault. Indeed, I repeated the same assumption: as the app closes after the screenshot without any note, I thought it was a crash. 

After checking the app, it works as expected. I'm sorry if I made you waste time. 

Thank you very much.

**Comment by dynobo** [comment]
> I'm sorry if I made you waste time.

No worries, I'm sure this issue will help others, too. (And it nudges me to improve the infos on the flathub page... :see_no_evil: )
