### ISSUE TITLE
Just an idea to do the impossible: fork Normcap to be a Web grabber.

### ISSUE THREAD

**Issue by rin67630** [dynobo/normcap#266]
I just thought: Normcap could be the base of a really powerful fancy Web grabber.
Some websites make it very difficult to grab some useful information, since their HTML5 is extremely dynamic and quasi impossible to grab by usual means.
Normcap could possibly be a way to bypass all the hurdles and just OCR a tiny part of the screen periodically and output the result into a JSON source.
Probably just add a timer and redirect the output to a JSON source.
What do you think about that idea?
Unfortunately, i am not skilled enough in Python to do it, being only a C++  hobby programmer.
Regards
Laszlo.

**Comment by dynobo** [comment]
Hi @rin67630, it's great to see that you like NormCap and think about using it for other purposes, too, thanks for that!  :blush: 

As you already suspected, your proposed idea is out of scope for NormCap. That's why I'll have to decline and close this is issue here, but please, feel free to use the ["discussions"](https://github.com/dynobo/normcap/discussions)-section, in case you want to further ideate on your proposal.

Best regards!
