### ISSUE TITLE
[Linux] Normcap for ARM64

### ISSUE THREAD

**Issue by archisman-panigrahi** [dynobo/normcap#321]
It would be great if you enable arm64 builds of Normcap in Flathub.
Nowadays, there are a lot of powerful ARM computers which can run GNU/Linux.

Since Normcap is written in Python, it should work out of the box on ARM.

**Comment by dynobo** [comment]
@apandada1, I agree it would be great to have NormCap working on ARM, too. 

As it is not super high on my list of priorities, and I also don't own an ARM device for testing, I'd be happy if someone could take a look at [NormCap's flatpak configs](https://github.com/flathub/com.github.dynobo.normcap) and give it a try! :-)

**Comment by apandada1** [comment]
I have a arm64 device running Ubuntu 22.04, but I don't know how to
generate a flatpak build. If someone can generate the flatpak, I will be
happy to test it.

**Comment by dynobo** [comment]
@apandada1 , it's actually quite easy. If you like to give it a try, just follow the [getting started guide](https://docs.flatpak.org/en/latest/first-build.html). Instead of Step 1 & 2, just clone [NormCap's Flatpak configs](https://github.com/flathub/com.github.dynobo.normcap) and use that manifest.

You might have to adapt the manifest to allow building on ARM, but that's something I don't know and would need to look up somewhere anyway.

**Comment by apandada1** [comment]
[Right now](https://github.com/flathub/com.github.dynobo.normcap/blob/3a0c2c696b0e9379aea968cca2ee03a494dbc542/python3-dependencies.json#L102) the flatpak builds from prebuilt python binaries for x86_64 architecture. Can this behavior be changed so that it builds everything (including python packages) from source?

**Comment by apandada1** [comment]
Consider for example, shiboken6. Do you think if I replace the whl URL (https://github.com/flathub/com.github.dynobo.normcap/blob/3a0c2c696b0e9379aea968cca2ee03a494dbc542/python3-dependencies.json#L112) with this source package ( https://download.qt.io/official_releases/QtForPython/shiboken6/PySide6-6.4.2-src/) it might work?

**Comment by dynobo** [comment]
@apandada1, at least _both_ sources for `python3-pyside6`-package, `shiboken6` _and_ `PySide6_Essentials` seem to be `x86_64` platform specific. I have no insights into how those two `.whl` files were build, but for a quick test, you could try to replace the `url`'s for both files with the respective `.tar.gz` urls you can find in the [qt download section](https://download.qt.io/official_releases/QtForPython/), which you mentioned. You also need to generate and replace the 'sha265' hashes. You don't have to adjust the `x-checker-data` patterns yet, we can figure that out later. Then could try to [build and test the flatpak locally](https://docs.flatpak.org/en/latest/first-build.html#test-the-build) on your arm64 machine and see if it works.

My gut feeling is, there is a fair chance that this could already be enough to get it to work. But it is also totally possible, that it's not as simple. But it's definitely worth a try!

**Comment by dynobo** [comment]
Closing this issue, in favor of tracking this topic in #567
