### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by tio-trom** [dynobo/normcap#445]
### What happened?

When I start it I get:

```
Traceback (most recent call last):
  File "/usr/bin/normcap", line 5, in <module>
    from normcap.app import main
ModuleNotFoundError: No module named 'normcap'
```

### How did you install NormCap?

Chaotic AUR

### Operating System + Version?

Manjaro Arch 

### [Linux only] Display Server (DS) + Desktop environment (DE)?

XFCE

### Debug log output?

```shell
Traceback (most recent call last):
  File "/usr/bin/normcap", line 5, in <module>
    from normcap.app import main
ModuleNotFoundError: No module named 'normcap'
```

**Comment by tio-trom** [comment]
Works from AUR probably a Chaotic AUR issue or incompatibility with my system. If you think that might be it please feel free to close this issue.

**Comment by dynobo** [comment]
@tio-trom, did you you recently upgrade your Python version? (I think Arch Linux distributed the update last week or so.) Because anytime a new major Python version get installed, you have to rebuild _all_ your (Python-based) AUR packages. 

The reason is, that the Python packages (and there dependencies) are getting installed for a specific Python version, and are not migrated over or something. This is the case for _all_  Python based packages, it's not a NormCap specific issue. It is a common issue, that's reoccuring every year after a Python major update. E.g. see [this comment in AUR](https://aur.archlinux.org/packages/gnome-browser-connector#comment-912685)

Do you think, this also might have been the reason for your issue?

**Comment by tio-trom** [comment]
Ah yes I am quite sure that must be it. Since I use Manjaro Arch and they have their own repos this is entirely possible. Thank you so much for the detailed explanation. I will close this issue since the AUR package works. Probably the normcap form the chaotic aur is built against a different version of Python than the one I have. If I build normcap from AUR all works great.
