### ISSUE TITLE
[Windows] Error on msi-installer v0.4.4. - Unable to uninstall previous version

### ISSUE THREAD

**Issue by bikelif3** [dynobo/normcap#464]
### What happened?

![normcap error](https://github.com/dynobo/normcap/assets/136023920/cb237394-42ff-4ea7-94d1-29dc08a0ced3)

When trying to update to v0.4.4 using windows msi installer, I get the error in the picture. After clicking CANCEL, installer says "older version can not be removed".

Any suggestions? Thanks.

### How did you install NormCap?

MSI installer (Windows)

### Operating System + Version?

Windows 10 Home

**Comment by bikelif3** [comment]
Instead of the windows installer I installed the python package and now have v0.4.4 running well. One tip is that you must run normcap script "minimized" so that it's not covering the screen you're trying to extract data.

**Comment by dynobo** [comment]
Thanks for reporting this bug, @bikelif3 . It was very likely introduced by a03f0828c0512f80affe7bc029e54e47e56c4b30, which introduced some changes to the Windows installer in the hope of fixing #452.

Could you please try to uninstall all previous Normcap Versions via Windows' "Add/Remove Software", and then install the current latest version again?

Meanwhile, I'll see if I can reproduce the issue and find a fix...

**Comment by bikelif3** [comment]
> Could you please try to uninstall all previous Normcap Versions via Windows' "Add/Remove Software", and then install the current latest version again?
> 

One of the first things I did was use Revo Uninstaller Pro to uninstall current version of NormCap. Revo deleted leftover registry entries and other NormCap folders/files that were leftover.

Tried to use msi installer v0.4.4 and got the same error.

**Comment by dynobo** [comment]
Thanks for this additional info, @bikelif3. I'll investigate this and post here, once I have an update.

**Comment by bikelif3** [comment]
Here's an update. I have v0.4.4 running well on my PC now. Here's what happened. I had v0.4.0 installed. Since the newer installers were looking for v0.3.14 msi installer I downloaded it from the prior releases. With the older installer on my desktop, the newer installers were able to proceed. For some reason I could only update to v0.4.3 and not v0.4.4. When checking Revo Uninstaller Pro I saw that there were actually 3 versions of normcap on my PC. So I checked the 3 versions, uninstalled, deleted leftover registry items and files. Finally, I downloaded v0.4.4 and was able to install it completely and it is now working.

**Comment by dynobo** [comment]
I looked into this issue: Due to some incompatible changes in the msi-installer, certain versions can't be upgraded:
- v0.4.1 and earlier can't be upgraded to v0.4.2 and later
- v0.4.4 and earlier can't be upgraded with the (upcoming) v0.5.0 and later

While we _try_ to avoid those breaks, we don't have the resources to totally _avoid_ them. 

**Recommendation: If upgrading with the Windows-Installer doesn't work for you, please uninstall all existing NormCap versions and do a fresh install of the newest Version.** (Doing so, your settings _might_ be reset and you _might_ have to re-download language files.)

If that doesn't help, please [create a new issue](https://github.com/dynobo/normcap/issues/new/choose).
