### ISSUE TITLE
Normcap windows notifications can't turned back on

### ISSUE THREAD

**Issue by Barisrky** [dynobo/normcap#87]
Before my i would like to thank you for application, it is just what i wanted. I am not a programmer of anykind i just wanted app like this for everyday use so here is my problem. I turned of the windows notifications form notifications area but it was a bad decision and i wanted to turn it back on but i can't find any option to turn the apps notifications on. I guess because app is working from a file and not installed the pc windows does not sees the app and i can't be found in the notifications settings. Because of that maybe there can be a another download option like a setup to improve notification settings etc. Or do you know i way i can handle this issue ?

**Comment by dynobo** [comment]
Hi @Barisrky,

thanks for the kind words and filing the issue. I tried also to re-enable the disabled notification and was very surprised that there seems to be no simple solution for that.

It seems like Normcap has to be prepared somehow to hook into Window 10's notification settings or something, but unfortunately I lack the necessary skills on Windows.

**I would be glad if somebody could help with this issue!**

During a 2 hours research I at least was able to re-enable the notification manually, but the procedure is so complicated that **I do not recommend to do this**, because it's is prone to breaking important system stuff. But as it might help others to find a _real_ solution or better workaround, I mention it anyway, but **try at your own risk:**

**Step 1:**
- In the Registry Editor, navigate to `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings\NormCap 0.1.6` and set the value of key `Enabled` to `1`

![step1](https://user-images.githubusercontent.com/11071876/98735166-3de52180-23a3-11eb-8012-4afc14104aea.PNG)

**Step 2:**
- Download a sqlite database editor like [sqlitebrowser](https://sqlitebrowser.org/dl/)
- With it, open the file `C:\Users\<USERNAME>\AppData\Local\Microsoft\Windows\Notifications\wpndatabase.db`
- Delete the record with `PrimaryId=Normcap 0.1.6` from the table `NotificationHandler`
- Save the changes (in sqlitebrowser, do "File" -> "Write Changes")
![step2](https://user-images.githubusercontent.com/11071876/98735196-48072000-23a3-11eb-9036-72f6c84763fe.PNG)

**Step 3:**
- Restart "Windows Explorer" from Task Manager
![step3](https://user-images.githubusercontent.com/11071876/98735213-4dfd0100-23a3-11eb-9e48-b67b3c4dc3be.PNG)

As I said, this approach is not suitable to end users and might break stuff. It might help other to come up with a better solution.

**Comment by ms7m** [comment]
Hey @dynobo  and @Barisrky,

Developer for the notification library here.

A workaround to "re-enabling" (not the best word here imo) is to **simply change the application ID** when creating the initial ``Notify`` object. It's up to you guys to determine a best route here but probably a quick and dirty way is to have a unique application name each time you send the notification.

I think I'll try to add a check to see if the notifications were blocked by the user, and offer a workaround internally to combat this. I opened a issue for you guys to keep track https://github.com/ms7m/notify-py/issues/21 on it.

**Comment by Barisrky** [comment]
I tried to find notification settings like in the @dynobo 's step 1 before but in my regedit notification settings there is no normcap and i quickly give up. I think i am going to wait a little for easier solution. Thank you both.

**Comment by dynobo** [comment]
@Barisrky : FYI, the [new release](https://github.com/dynobo/normcap/releases/tag/v0.1.7) comes with a new application new (the version in it has changed), which should re-enable your notification. The **underlying issue however is not fixed yet**, so don't try to disable the notifications if you want to keep them... ;-)

**Comment by Barisrky** [comment]
Oh thanks, i learned it from the hard way to not disable notifications right away :D. But i tried new release now and i get "failed to execute script __main__ " error :/

**Comment by dynobo** [comment]
@Barisrky, I also noticed some issues in the newest release... Would you mind opening a new issues for that, and posting the complete error message? If possible after starting with `normcap --verbose`? Thanks!

**Comment by dynobo** [comment]
When #91 and #92 are solved, I can implement a function to get the AppID (maybe parsing `Get-StartApps` command output?) and use that AppID when triggering the notification. This should make normcap appear in "Notifications & Actions"-Settings.

**Comment by dynobo** [comment]
This issue should be solved with the new `...installer.exe`, which is build for v0.1.9 and above and can be downloaded from the [releases-page](https://github.com/dynobo/normcap/releases). The installer also comes with the benefits of creating an application shortcut in the start menu and allowing uninstall through "Add/remove programs".

For the "old" installation-methods, zip-file (portable) and python package, this issue will persist: I think it's bad practice to integrate those "installation" into the system to deep (like manipulating windows registry). 

I would be happy to know, if this solutions works for you or not! :-)
